# generated by datamodel-codegen:
#   filename:  models.yaml
#   timestamp: 2025-08-29T12:42:26+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    Field,
    RootModel,
    confloat,
    constr,
)


class FertilizerApplication(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    application_depth_fert: Optional[Any] = Field(
        None, description='Fertilizer application depth'
    )
    ca_in_applied_fertilizer: Optional[Any] = Field(
        None, description='Ca in applied fertilizer'
    )
    category: Optional[Any] = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Optional[Any] = Field(
        None, description='Date when the operation was executed'
    )
    fertiliz_app_name: Optional[Any] = Field(
        None, description='Name or notes for this fertilizer application'
    )
    fertiliz_code_other_elem: Optional[Any] = Field(
        None, description='Fertilizer code for other elements (e.g., Mg for magnesium)'
    )
    fertilization_date: date = Field(..., description='Fertilization date')
    fertilizer_applic_day: Optional[Any] = Field(
        None, description='Fertilizer application day'
    )
    fertilizer_applic_method: Optional[Any] = Field(
        None, description='Fertilizer application method'
    )
    fertilizer_applic_year: Optional[Any] = Field(
        None, description='Fertilizer application year'
    )
    fertilizer_k_applied: Optional[Any] = Field(
        None, description='Potassium in applied fertilizer'
    )
    fertilizer_level: Optional[Any] = Field(
        None, description='Fertilizer level in treatment structure'
    )
    fertilizer_material: Optional[Any] = Field(None, description='Fertilizer material')
    id: Any = Field(..., description='nglsi-id id')
    n_in_applied_fertilizer: float = Field(
        ..., description='Nitrogen in applied fertilizer'
    )
    nh4_applied_fertilizer: Optional[Any] = Field(
        None, description='Ammonium in applied fertilizer'
    )
    no3_applied_fertilizer: Optional[Any] = Field(
        None, description='Nitrate applied fertilizer'
    )
    other_elements_appl_fert: Optional[Any] = Field(
        None, description='Other elements in applied fertilizer'
    )
    phosphorus_applied_fert: Optional[Any] = Field(
        None, description='Phosphorus in applied fertilizer'
    )
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be FertilizerApplication')


class HarvestEvent(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Optional[Any] = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Optional[Any] = Field(
        None, description='Date when the operation was executed'
    )
    harv_operat_main_product: Optional[Any] = Field(
        None, description='Harvest operations, percent economic product harvested'
    )
    harv_operat_size_categor: Optional[Any] = Field(
        None, description='Harvest operations size category'
    )
    harv_operation_byproduct: Optional[Any] = Field(
        None, description='Harvest operations, percent of by-product harvested'
    )
    harvest_amount: float = Field(
        ..., description='Harvest, total amount removed as mass'
    )
    harvest_area: Optional[Any] = Field(None, description='Harvest area')
    harvest_crop: Optional[Any] = Field(
        None, description='Harvest operations, crop harvested'
    )
    harvest_cut_height: Optional[Any] = Field(
        None, description='Harvest, height of cut'
    )
    harvest_method: Optional[Any] = Field(None, description='Harvest method')
    harvest_operat_component: Optional[Any] = Field(
        None, description='Harvest operations, crop component harvested'
    )
    harvest_operations_date: date = Field(
        ..., description='Harvest operations date, DAP if year = -99'
    )
    harvest_operations_day: Optional[Any] = Field(
        None, description='Harvest operations day, DAP if year = -99'
    )
    harvest_operations_level: Optional[Any] = Field(
        None, description='Harvest operations level, links to HARVEST table'
    )
    harvest_operations_year: Optional[Any] = Field(
        None, description='Harvest operations year'
    )
    harvest_stage: Optional[Any] = Field(
        None, description='Harvest, growth stage of crop at date'
    )
    id: Any = Field(..., description='nglsi-id id')
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be HarvestEvent')


class IrrigationApplication(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    bund_height: Optional[Any] = Field(
        None, description='Bund height (e.g., for flooded rice)'
    )
    category: Optional[Any] = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Optional[Any] = Field(
        None, description='Date when the operation was executed'
    )
    id: Any = Field(..., description='nglsi-id id')
    irrig_amount_depth: Optional[Any] = Field(
        None, description='Irrigation amount, depth of water'
    )
    irrigation_applic_depth: Optional[Any] = Field(
        None, description='Irrigation application depth (e.g., for depth to drip line)'
    )
    irrigation_date: date = Field(..., description='Irrigation date')
    irrigation_day: Optional[Any] = Field(None, description='Irrigation day')
    irrigation_h2o_n_conc: Optional[Any] = Field(
        None, description='Irrigation water nitrogen concentration'
    )
    irrigation_level: Optional[Any] = Field(
        None, description='Irrigation level, links to IRRIGATIONS table'
    )
    irrigation_operation: Optional[Any] = Field(
        None, description='Irrigation operation (e.g., furrow, sprinkler, drip…)'
    )
    irrigation_operation_name: Optional[Any] = Field(
        None,
        description='Name of irrigation operation or specific notes about this application',
    )
    irrigation_year: Optional[Any] = Field(
        None, description='Irrigation or water management year'
    )
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be IrrigationApplication')


class OrganicMaterialApplication(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Optional[Any] = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Optional[Any] = Field(
        None, description='Date when the operation was executed'
    )
    id: Any = Field(..., description='nglsi-id id')
    org_material_appl_depth: Optional[Any] = Field(
        None, description='Organic materials application depth'
    )
    org_material_applic_amnt: float = Field(
        ..., description='Organic materials application amount, dry weight basis'
    )
    org_material_applic_date: date = Field(
        ..., description='Organic materials application date'
    )
    org_material_applic_day: Optional[Any] = Field(
        None, description='Organic materials application day'
    )
    org_material_applic_meth: Optional[Any] = Field(
        None, description='Organic materials application method'
    )
    org_material_c_to_n: float = Field(..., description='Organic materials C:N ratio')
    org_material_cover: Optional[Any] = Field(
        None, description='Organic materials, percent ground covered by organic matter'
    )
    org_material_incorp_perc: Optional[Any] = Field(
        None, description='Organic materials application, fraction incorporporated as %'
    )
    org_material_lignin_conc: Optional[Any] = Field(
        None, description='Organic materials lignin concentration'
    )
    org_materials_applic_lev: Optional[Any] = Field(
        None, description='Organic materials application level, links to OM table'
    )
    org_materials_applic_yr: Optional[Any] = Field(
        None, description='Organic materials application year'
    )
    org_matter_carbon_conc: Optional[Any] = Field(
        None, description='Organic matter or residue added, carbon concentration'
    )
    org_matter_moisture_conc: Optional[Any] = Field(
        None, description='Organic matter or residue added, moisture concentration'
    )
    organic_material: str = Field(..., description='Organic material, identifying code')
    organic_material_k_conc: Optional[Any] = Field(
        None, description='Organic materials potasium concentration'
    )
    organic_material_n_conc: float = Field(
        ..., description='Organic materials nitrogen concentration'
    )
    organic_material_p_conc: Optional[Any] = Field(
        None, description='Organic materials phosphorus concentration'
    )
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(
        ..., description='nglsi-id type, has to be OrganicMaterialApplication'
    )


class Planting(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Optional[Any] = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    crop_code: Optional[Any] = Field(None, description='ICASA crop code')
    crop_common_name: str = Field(..., description='ICASA crop common name')
    cultivar_name: str = Field(..., description='ICASA cultivar name')
    dateObserved: Optional[Any] = Field(
        None, description='Date when the operation was executed'
    )
    emergence_date: Optional[Any] = Field(None, description='Date of emergence')
    emergence_day: Optional[Any] = Field(
        None, description='Day of year for date of emergence'
    )
    emergence_year: Optional[Any] = Field(
        None, description='Year for date of emergence (growth stage)'
    )
    fertile_tiller_num: Optional[Any] = Field(
        None, description='Fertile tiller number (sorghum)'
    )
    germination: Optional[Any] = Field(
        None, description='Planting material germination'
    )
    id: Any = Field(..., description='nglsi-id id')
    length_sprout_material: Optional[Any] = Field(
        None, description='Planting material sprout length'
    )
    nursery_env_pl_material: Optional[Any] = Field(
        None, description='Transplant nursery environment (mean temperature)'
    )
    plant_pop_at_emergence: Optional[Any] = Field(
        None, description='Plant population at emergence'
    )
    plant_pop_at_planting: Optional[Any] = Field(
        None, description='Plant population at planting'
    )
    planting_date: date = Field(..., description='Planting or sowing date')
    planting_day: Optional[Any] = Field(None, description='Day of planting')
    planting_depth: Optional[Any] = Field(None, description='Planting depth')
    planting_distribution: Optional[Any] = Field(
        None, description='Planting distribution'
    )
    planting_level: Optional[Any] = Field(
        None, description='Planting, level in treatment structure'
    )
    planting_level_name: Optional[Any] = Field(
        None, description='Planting level, name of treatment'
    )
    planting_material: Optional[Any] = Field(None, description='Planting material')
    planting_material_age: Optional[Any] = Field(
        None, description='Planting material age (also used for dormancy adjustments)'
    )
    planting_material_source: Optional[Any] = Field(
        None, description='Source of the planting material'
    )
    planting_material_weight: Optional[Any] = Field(
        None, description='Planting material weight'
    )
    planting_year: Optional[Any] = Field(None, description='Planting year')
    plants_per_hill: Optional[Any] = Field(None, description='Plants per hill')
    row_direction: Optional[Any] = Field(
        None, description='Row direction, degrees from N'
    )
    row_spacing: Optional[Any] = Field(None, description='Row spacing')
    seedbed_density: Optional[Any] = Field(
        None, description='Planting density in nursery seed bed'
    )
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    transplant_age: Optional[Any] = Field(None, description='Transplant age')
    transplant_date: Optional[Any] = Field(None, description='Transplant date')
    type: Any = Field(..., description='nglsi-id type, has to be Planting')


class TillageEvent(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Optional[Any] = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Optional[Any] = Field(
        None, description='Date when the operation was executed'
    )
    id: Any = Field(..., description='nglsi-id id')
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    till_mix_effectiveness: Optional[Any] = Field(
        None, description='Tillage operations mixing effectiveness'
    )
    tillage_date: date = Field(..., description='Tillage date')
    tillage_implement: Optional[Any] = Field(None, description='Tillage implement')
    tillage_level: Optional[Any] = Field(None, description='Tillage operation level')
    tillage_operation_name: str = Field(
        ..., description='Tillage operations, name of specific event'
    )
    tillage_operations_day: Optional[Any] = Field(
        None, description='Tillage operations day'
    )
    tillage_operations_depth: Optional[Any] = Field(
        None, description='Tillage operations depth'
    )
    tillage_operations_year: Optional[Any] = Field(
        None, description='Tillage operations year'
    )
    tillage_order: Optional[Any] = Field(
        None, description='Tillage operations order within a single day'
    )
    type: Any = Field(..., description='nglsi-id type, has to be TillageEvent')


class Genotype(BaseModel):
    agriparcel: Optional[Any] = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    crop_ident_icasa: Optional[Any] = Field(
        None, description='Crop (or weed) species identifier'
    )
    cultivar_identifier: Optional[Any] = Field(
        None, description='Cultivar, line or genotype identifier'
    )
    cultivar_name: Optional[Any] = Field(None, description='Cultivar name')
    cultivar_notes: Optional[Any] = Field(None, description='Cultivar notes')
    genotype_level_number: Optional[Any] = Field(
        None, description='Genotype level, as listed in Treatments table under GE'
    )
    id: Optional[Any] = Field(None, description='id')
    relative_maturity: Optional[Any] = Field(None, description='Relative maturity')
    type: Any = Field(..., description='nglsi-id type, has to be Genotype')


class Soil(BaseModel):
    agriparcel: Optional[Any] = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    distrib_restrictions: Optional[Any] = Field(
        None, description='Distribution limitations for the soils data set'
    )
    file_version_sl: Optional[Any] = Field(
        None, description='File version for ICASA standard'
    )
    id: Any = Field(..., description='nglsi-id id')
    revision_date_first_sl: Optional[Any] = Field(
        None, description='Date the file was first created'
    )
    revision_date_latest_sl: Optional[Any] = Field(
        None, description='Date the file was last modified'
    )
    revision_notes_sl: Optional[Any] = Field(
        None, description='Notes describing reasons for the revision'
    )
    soil_citation: Optional[Any] = Field(
        None, description='Full citation for soil data'
    )
    soil_license: Optional[Any] = Field(
        None, description='License associated with soil data'
    )
    soil_notes: Optional[Any] = Field(None, description='Notes describing soil dataset')
    soil_profile_methods: Optional[Any] = Field(
        None, description='General notes on execution of experiment.'
    )
    type: Any = Field(..., description='nglsi-id type, has to be Soil')


class SoilProfile(BaseModel):
    agriparcel: Optional[Any] = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    cona: Optional[Any] = Field(None, description='Apsim Cona soil evaporation ')
    depth_of_topsoil: Optional[Any] = Field(None, description='Thickness of topsoil')
    diffus_const: Optional[Any] = Field(
        None, description='APSIM Evaporative diffusion constant'
    )
    diffus_slope: Optional[Any] = Field(
        None, description='APSIM Evaporative diffusion slope'
    )
    drainage_rate_per_day: Optional[Any] = Field(
        None, description='Drainage rate as fraction per day'
    )
    id: Any = Field(..., description='nglsi-id id')
    latitude_soil_profile: Optional[Any] = Field(
        None, description='Latitude of soil profile site'
    )
    longitude_soil_profile: Optional[Any] = Field(
        None, description='Longitude of soil profile site'
    )
    mineralization_factor: Optional[Any] = Field(
        None, description='Mineralization factor (0 to 1 scale)'
    )
    name_of_soil_profile: Optional[Any] = Field(
        None, description='Name of soil profile'
    )
    ph_buffer_determin_meth: Optional[Any] = Field(
        None, description='pH in buffer determination method'
    )
    phosphorus_determ_method: Optional[Any] = Field(
        None, description='Phosphorus determination method'
    )
    potassium_determ_method: Optional[Any] = Field(
        None, description='Potassium determination method'
    )
    runoff_curve_no_scs: Optional[Any] = Field(
        None, description='Runoff curve no. (Soil Conservation Service)'
    )
    soil_albedo: Optional[Any] = Field(None, description='Soil albedo, dry soil')
    soil_albedo_moist: Optional[Any] = Field(
        None, description='Soil albedo, moist soil'
    )
    soil_classific_system: Optional[Any] = Field(
        None, description='Soil classification system (e.g., FAO, USDA)'
    )
    soil_classification: Optional[Any] = Field(None, description='Soil classification')
    soil_denitrification_fac: Optional[Any] = Field(
        None, description='Soil denitrification factor'
    )
    soil_depth: Optional[Any] = Field(None, description='Soil depth')
    soil_evaporation_limit: Optional[Any] = Field(
        None, description='Soil evaporation, upper limit for stage 1'
    )
    soil_fertility_on_photo: Optional[Any] = Field(
        None, description='Soil fertility effect on photosynthesis (0 to 1 scale)'
    )
    soil_file_id: Optional[Any] = Field(None, description='Soil profile file name')
    soil_id: Optional[Any] = Field(
        None, description='Unique soil identifier linking to SOIL_PROFILES'
    )
    soil_loc_2nd_level: Optional[Any] = Field(
        None,
        description='Second admin level for location of site for soil profile (usually state or province)',
    )
    soil_loc_3rd_level: Optional[Any] = Field(
        None,
        description='Third admin level for location of site for soil profile (usually county or municipality)',
    )
    soil_location_country: Optional[Any] = Field(
        None,
        description='First admin for location of site for soil profile (usually country)',
    )
    soil_profile_id: Optional[Any] = Field(None, description='Soil profile identifier')
    soil_profile_slope: Optional[Any] = Field(
        None, description='Slope where soil profile characterized'
    )
    soil_site: Optional[Any] = Field(
        None, description='Name of site where soil profile data sampled'
    )
    soil_site_elevation: Optional[Any] = Field(
        None, description='Elevation of soil profile site'
    )
    soil_surface_color: Optional[Any] = Field(
        None, description='Surface soil color, moist, using Munsell hue'
    )
    soil_texture: Optional[Any] = Field(None, description='Soil texture')
    summer_u: Optional[Any] = Field(
        None, description='Summer soil evaporation, upper limit for stage 1'
    )
    surface_stones__cover_: Optional[Any] = Field(
        None, alias='surface_stones_(cover)', description='Surface stones (cover)'
    )
    type: Any = Field(..., description='nglsi-id type, has to be SoilProfile')
    winter_u: Optional[Any] = Field(
        None, description='Winter soil evaporation, upper limit for stage 1'
    )


class SoilProfileLayer(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    caco3_content: Optional[Any] = Field(None, description='Soil CaCO3 content')
    cation_exchange_capacity: Optional[Any] = Field(
        None, description='Cation exchange capacity'
    )
    date: Optional[Any] = Field(None, description='Date of observation')
    electric_conductivity: Optional[Any] = Field(
        None, description='Electric conductivity'
    )
    grid_id: Optional[Any] = Field(
        None, description='Id of the cell on the chosen grid, e.g. h3 grid id'
    )
    id: Any = Field(..., description='nglsi-id id')
    iron: Optional[Any] = Field(None, description='Iron')
    layer_drainage_rate_per_day: Optional[Any] = Field(
        None, description='Drainage rate as fraction per day, per layer'
    )
    master_horizon: Optional[Any] = Field(None, description='Master horizon')
    nh4soil_kcl: Optional[Any] = Field(
        None, description='NH4 in soil based on KCl extraction, by layer'
    )
    nitrate_kcl: Optional[Any] = Field(
        None, description='Nitrate in soil based on KCl extraction, by layer'
    )
    phosphorus_extractable: Optional[Any] = Field(
        None, description='Phosphorus, extractable'
    )
    phosphorus_iostherm_b: Optional[Any] = Field(
        None, description='Phosphorus iostherm B'
    )
    phosphorus_isotherm_a: Optional[Any] = Field(
        None, description='Phosphorus isotherm A'
    )
    phosphorus_organic: Optional[Any] = Field(None, description='Phosphorus, organic')
    phosphorus_total: Optional[Any] = Field(None, description='Phosphorus, total')
    plant_root_uptake_factor: Optional[Any] = Field(
        None, description='APSIM plant specific water uptake coefficient'
    )
    potassium_exchangeable: Optional[Any] = Field(
        None, description='Potassium, exchangeable'
    )
    root_growth_factor_soil: Optional[Any] = Field(
        None, description='Root growth factor, soil only (0 to 1 scale)'
    )
    sat_hydraul_conductivity: Optional[Any] = Field(
        None, description='Saturated hydraulic conductivity'
    )
    soil_active_c: Optional[Any] = Field(
        None, description='Biologically active soil organic carbon by layer'
    )
    soil_active_c_fraction: Optional[Any] = Field(
        None,
        description='Biologically active soil organic carbon by layer, fraction of total organic C',
    )
    soil_adsorption_coef: Optional[Any] = Field(
        None, description='Soil adsorption coefficient (0 to 1 scale)'
    )
    soil_aluminum_conc: Optional[Any] = Field(
        None, description='Soil aluminum concentration in profile described'
    )
    soil_base_saturation: Optional[Any] = Field(
        None, description='Soil base saturation'
    )
    soil_bulk_density_moist: Optional[Any] = Field(
        None, description='Soil bulk density when moist for layer'
    )
    soil_calcium_conc: Optional[Any] = Field(
        None, description='Soil calcium, exchangeable'
    )
    soil_clay_fraction: float = Field(
        ..., description='Soil texture, clay (<0.002 mm), weight percent of fine earth'
    )
    soil_coarse_fraction: Optional[Any] = Field(
        None,
        description='Soil texture, coarse fraction (>2 mm), weight percent of fine earth',
    )
    soil_color_moist_munsell: Optional[Any] = Field(
        None, description='Soil color of moist soil using Munsell hue'
    )
    soil_compac_fact_by_lyr: Optional[Any] = Field(
        None, description='Soil compaction factor by layer (0 to 1 scale)'
    )
    soil_file_id: Optional[Any] = Field(None, description='Soil profile file name')
    soil_id: Optional[Any] = Field(
        None, description='Unique soil identifier linking to SOIL_PROFILES'
    )
    soil_inert_c: Optional[Any] = Field(
        None, description='Inert organic carbon by layer'
    )
    soil_inert_c_fraction: Optional[Any] = Field(
        None, description='Inert organic carbon by layer, fraction of total organic C'
    )
    soil_intermediate_c: Optional[Any] = Field(
        None, description='Intermediate soil organic carbon by layer'
    )
    soil_intermediate_c_fraction: Optional[Any] = Field(
        None,
        description='Intermediate soil organic carbon by layer, fraction of total organic C',
    )
    soil_layer_base_depth: float = Field(..., description='Soil layer base depth')
    soil_layer_top_depth: float = Field(..., description='Soil layer top depth')
    soil_magnesium_conc: Optional[Any] = Field(None, description='Magnesium')
    soil_manganese_conc: Optional[Any] = Field(None, description='Manganese')
    soil_organic_c_perc_layr: float = Field(
        ..., description='Total soil organic carbon by layer'
    )
    soil_organic_n_conc: Optional[Any] = Field(
        None, description='Nitrogen, total soil organic'
    )
    soil_ph_in_buffer: Optional[Any] = Field(
        None,
        description='pH of soil measured in buffer solution, from profile description',
    )
    soil_ph_in_water: Optional[Any] = Field(
        None, description='pH of soil in water, from profile description'
    )
    soil_profile_id: Optional[Any] = Field(None, description='Soil profile identifier')
    soil_sand_fraction: float = Field(
        ...,
        description='Soil texture, sand (0.05 to 2.0 mm), weight percent of fine earth',
    )
    soil_silt_fraction: float = Field(
        ...,
        description='Soil texture, silt (0.05 to 0.002 mm), weight percent of fine earth',
    )
    soil_sodium_conc: Optional[Any] = Field(None, description='Sodium in soil layer')
    soil_stable_c: Optional[Any] = Field(
        None, description='Stable organic carbon by layer'
    )
    soil_stable_c_fraction: Optional[Any] = Field(
        None, description='Stable organic carbon by layer, fraction of total organic C'
    )
    soil_sulphur_conc: Optional[Any] = Field(None, description='Sulphur in soil layer')
    soil_type: Optional[Any] = Field(None, description='Finnish soil type')
    soil_wat_drned_upper_lim: Optional[Any] = Field(
        None, description='Soil water, drained upper limit'
    )
    soil_water_air_dry: Optional[Any] = Field(
        None, description='Soil water content, air dry'
    )
    soil_water_field_cap_1: float = Field(
        ..., description='Soil water content at 1/3 atmosphere pressure'
    )
    soil_water_field_cap_2: float = Field(
        ..., description='Soil water content at 1/10 atmospheric pressure'
    )
    soil_water_lower_limit: Optional[Any] = Field(
        None, description='Soil water, lower limit'
    )
    soil_water_residual: Optional[Any] = Field(None, description='Soil water, residual')
    soil_water_saturated: float = Field(..., description='Soil water, saturated')
    soil_water_uptake_factor: Optional[Any] = Field(
        None, description='Root exploration factor (0 to 1 scale, APSIM XF)'
    )
    soil_water_wilting_pt: float = Field(
        ..., description='Soil water content (wilting point) at 15 atmosphere pressure '
    )
    spatial_category: Optional[Any] = Field(
        None,
        description='Category of the soil profile layer and related agriparcel. Same soil profile layer is created as both spatial_category h3 and basefield entities.So duplicates of the soil profile layers exist, soil profile layers have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be SoilProfileLayer')
    van_genuch_alpha: Optional[Any] = Field(
        None, description='Van Genuchten alpha parameter'
    )
    van_genuch_n: Optional[Any] = Field(None, description='Van Genuchten N parameter')
    year: Optional[Any] = Field(None, description='Year of observation')


class AgriFarm(BaseModel):
    agriparcel: Optional[Any] = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    id: Any = Field(..., description='nglsi-id id')
    legalid: Optional[Any] = Field(None, description='Legal id of the farm')
    type: Any = Field(..., description='nglsi-id type, has to be AgriFarm')


class FieldParcel(BaseModel):
    agriparcel: Optional[Any] = Field(None, description='Reference to the AgriParcel')
    area: Optional[confloat(ge=0.0)] = Field(
        None, description='The area of the parcel nominally in square meters.'
    )
    farm: Optional[str] = Field(None, description='Reference to farm.')
    id: Any = Field(..., description='nglsi-id id')
    location: Optional[Any] = Field(
        None,
        description='GeoProperty. Geojson reference to the item.',
        title='GeoJSON Polygon',
    )
    name: Optional[Any] = Field(None, description='Name of the parcel')
    parcelid: Optional[Any] = Field(None, description='Parcel id')
    resolution: Optional[Any] = Field(
        None, description='Spatial resolution, especially for h3 cells'
    )
    spatial_category: Optional[Any] = Field(
        None, description="Parcel type. 'Enum:' `base`, `growth`, `h3`"
    )
    type: Any = Field(..., description='nglsi-id type, has to be FieldParcel')
    year: Optional[Any] = Field(None, description='Registration year')


class Eo(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    id: Any = Field(..., description='nglsi-id id')
    leaf_area_index: Optional[Any] = Field(
        None, description='Leaf area index on a given day'
    )
    observation_date: date = Field(..., description='Observation date of eo data')
    type: Any = Field(..., description='nglsi-id type, has to be Eo')


class Sample(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    grid_id: Optional[Any] = Field(
        None, description='Id to locate sample on chosen grid, e.g. h3 id'
    )
    id: Any = Field(..., description='nglsi-id id')
    location: Optional[Any] = Field(
        None, description='Geometry of the sample, e.g. Point or Polygon'
    )
    sampling_date: date = Field(..., description='Sampling date')
    soil_organic_C_perc_layr: Optional[Any] = Field(
        None,
        description='Total soil organic carbon by layer, expressed as g[C]/100g[soil]',
    )
    soil_organic_matter_layer: Optional[Any] = Field(
        None, description='Total soil organic matter by layer'
    )
    soil_pH_in_buffer: Optional[Any] = Field(
        None,
        description='pH of soil measured in buffer solution, from profile description',
    )
    soil_pH_in_water: Optional[Any] = Field(
        None, description='pH of soil in water, from profile description'
    )
    total_biomass_dry_wt: Optional[Any] = Field(
        None, description='Total biomass without senesced material (dry weight, kg/ha)'
    )
    type: Any = Field(..., description='nglsi-id type, has to be Sample')


class Address(BaseModel):
    addressCountry: Optional[str] = Field(
        None, description='The country. For example, Spain'
    )
    addressLocality: Optional[str] = Field(
        None,
        description='The locality in which the street address is, and which is in the region',
    )
    addressRegion: Optional[str] = Field(
        None,
        description='The region in which the locality is, and which is in the country',
    )
    district: Optional[str] = Field(
        None,
        description='A district is a type of administrative division that, in some countries, is managed by the local government',
    )
    postOfficeBoxNumber: Optional[str] = Field(
        None,
        description='The post office box number for PO box addresses. For example, 03578',
    )
    postalCode: Optional[str] = Field(
        None, description='The postal code. For example, 24004'
    )
    streetAddress: Optional[str] = Field(None, description='The street address')
    streetNr: Optional[str] = Field(
        None, description='Number identifying a specific property on a public street'
    )


class AirTemperatureTSA(BaseModel):
    averageValue: Optional[float] = Field(
        None, description='Average value of temporal processing over time'
    )
    instValue: Optional[float] = Field(
        None, description='Instant value of temporal processing'
    )
    maxOverTime: Optional[float] = Field(
        None, description='Maximum value of temporal processing over time'
    )
    minOverTime: Optional[float] = Field(
        None, description='Minimum value of temporal processing over time'
    )


class Type(Enum):
    Point = 'Point'


class Location(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[float] = Field(..., min_length=2)
    type: Type


class Coordinate(RootModel[List[Any]]):
    root: List[Any]


class Type1(Enum):
    LineString = 'LineString'


class Location1(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[Coordinate] = Field(..., min_length=2)
    type: Type1


class Type2(Enum):
    Polygon = 'Polygon'


class Location2(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[Coordinate]]
    type: Type2


class Type3(Enum):
    MultiPoint = 'MultiPoint'


class Location3(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[float]]
    type: Type3


class Type4(Enum):
    MultiLineString = 'MultiLineString'


class Location4(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[Coordinate]]
    type: Type4


class Type5(Enum):
    MultiPolygon = 'MultiPolygon'


class Location5(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[List[Coordinate]]]
    type: Type5


class PressureTendency(Enum):
    falling = 'falling'
    raising = 'raising'
    steady = 'steady'


class Type6(Enum):
    WeatherObserved = 'WeatherObserved'


class Visibility(Enum):
    veryPoor = 'veryPoor'
    poor = 'poor'
    moderate = 'moderate'
    good = 'good'
    veryGood = 'veryGood'
    excellent = 'excellent'


class WeatherObserved(BaseModel):
    address: Optional[Address] = Field(None, description='The mailing address')
    agriparcel: Optional[Any] = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    airQualityIndex: Optional[float] = Field(
        None,
        description='Air quality index is a number used to report the quality of the air on any given day',
    )
    airQualityIndexForecast: Optional[float] = Field(
        None,
        description='Forecasted overall Air Quality Index (AQI) over a certain duration in future',
    )
    airTemperatureForecast: Optional[float] = Field(
        None,
        description='Forecasted value of air temperature over a certain duration in future',
    )
    airTemperatureTSA: Optional[AirTemperatureTSA] = Field(
        None, description='Air temperature time series aggregation'
    )
    alternateName: Optional[str] = Field(
        None, description='An alternative name for this item'
    )
    aqiMajorPollutant: Optional[str] = Field(
        None, description='Major pollutant in the Air Quality Index (AQI)'
    )
    aqiMajorPollutantForecast: Optional[str] = Field(
        None,
        description='Forecasted major air pollutant in the Air Quality Index (AQI) over a certain duration in future',
    )
    areaServed: Optional[str] = Field(
        None,
        description='The geographic area where a service or offered item is provided',
    )
    atmosphericPressure: Optional[confloat(ge=0.0)] = Field(
        None, description='The atmospheric pressure observed measured in Hecto Pascals'
    )
    dataProvider: Optional[str] = Field(
        None,
        description='A sequence of characters identifying the provider of the harmonised data entity',
    )
    dateCreated: Optional[AwareDatetime] = Field(
        None,
        description='Entity creation timestamp. This will usually be allocated by the storage platform',
    )
    dateModified: Optional[AwareDatetime] = Field(
        None,
        description='Timestamp of the last modification of the entity. This will usually be allocated by the storage platform',
    )
    dateObserved: AwareDatetime = Field(
        ..., description='Date of the observed entity defined by the user'
    )
    description: Optional[str] = Field(None, description='A description of this item')
    dewPoint: Optional[float] = Field(
        None,
        description='The dew point encoded as a number. Observed temperature to which air must be cooled to become saturated with water vapor',
    )
    diffuseIrradiation: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Diffuse irradiance is the part of the solar irradiance that is scattered by the atmosphere',
    )
    directIrradiation: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Direct irradiance is the part of the solar irradiance that directly reaches a surface',
    )
    feelsLikeTemperature: Optional[float] = Field(
        None, description='Temperature appreciation of the item'
    )
    gustSpeed: Optional[float] = Field(
        None,
        description='A sudden burst of high-speed wind over the observed average wind speed lasting only for a few seconds',
    )
    id: Union[
        constr(
            pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$', min_length=1, max_length=256
        ),
        AnyUrl,
    ] = Field(..., description='Unique identifier of the entity')
    illuminance: Optional[confloat(ge=0.0)] = Field(
        None,
        description='(https://en.wikipedia.org/wiki/Illuminance) observed measured in lux (lx) or lumens per square metre (cd·sr·m−2)',
    )
    location: Union[Location, Location1, Location2, Location3, Location4, Location5] = (
        Field(
            ...,
            description='Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon',
        )
    )
    name: Optional[str] = Field(None, description='The name of this item')
    owner: Optional[
        List[
            Union[
                constr(
                    pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$',
                    min_length=1,
                    max_length=256,
                ),
                AnyUrl,
            ]
        ]
    ] = Field(
        None,
        description='A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)',
    )
    precipitation: Optional[confloat(ge=0.0)] = Field(
        None, description='Amount of water rain registered. '
    )
    precipitationForecast: Optional[float] = Field(
        None, description='Forecasted rainfall over a certain duration in future'
    )
    pressureTendency: Optional[Union[PressureTendency, float]] = Field(
        None,
        description="Enum:'falling, raising, steady'. Is the pressure rising or falling? It can be expressed in quantitative terms or qualitative terms",
    )
    refDevice: Optional[
        Union[
            constr(
                pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!, :\\]+$',
                min_length=1,
                max_length=256,
            ),
            AnyUrl,
        ]
    ] = Field(
        None, description='A reference to the device(s) which captured this observation'
    )
    refPointOfInterest: Optional[str] = Field(
        None, description='Point of interest related to the item'
    )
    relativeHumidity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description='Humidity in the Air. Observed instantaneous relative humidity (water vapour in air)',
    )
    relativeHumidityForecast: Optional[float] = Field(
        None,
        description='Forecasted relative humidity (water vapour in air) over a certain duration in future',
    )
    seeAlso: Optional[Union[List[AnyUrl], AnyUrl]] = Field(
        None, description='list of uri pointing to additional resources about the item'
    )
    snowHeight: Optional[confloat(ge=0.0)] = Field(
        None,
        description='The snow height observed by generic snow depth measurement sensors, expressed in centimeters',
    )
    solarRadiation: Optional[confloat(ge=0.0)] = Field(
        None, description='The solar radiation observed measured in Watts per square'
    )
    source: Optional[str] = Field(
        None,
        description='A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object',
    )
    streamGauge: Optional[confloat(ge=0.0)] = Field(
        None,
        description='The water level surface elevation observed by Hydrometric measurement sensors, namely a [Stream Gauge](https://en.wikipedia.org/wiki/Stream_gauge) expressed in centimeters',
    )
    temperature: Optional[float] = Field(None, description='Temperature of the item')
    type: Type6 = Field(
        ..., description='NGSI Entity type. It has to be WeatherObserved'
    )
    uVIndexMax: Optional[confloat(ge=0.0)] = Field(
        None,
        description="The maximum UV index for the period, based on the World Health Organization's UV Index measure. [http://www.who.int/uv/intersunprogramme/activities/uv_index/en/](http://www.who.int/uv/intersunprogramme/activities/uv_index/en/) the values between 1 and 11 are the valid range for the index. The value 0 is for describing that no signal is detected so no value is stored",
    )
    visibility: Optional[Union[Visibility, confloat(ge=0.0)]] = Field(
        None, description='Categories of visibility'
    )
    weatherType: Optional[str] = Field(
        None, description='Text description of the weather'
    )
    windDirection: Optional[confloat(ge=0.0, le=360.0)] = Field(
        None, description='Direction of the wind bet'
    )
    windSpeed: Optional[confloat(ge=0.0)] = Field(
        None, description='Intensity of the wind'
    )


class DayMaximum(BaseModel):
    feelLikesTemperature: Optional[float] = Field(
        None, description='Temperature appreciation of the item'
    )
    relativeHumidity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description='Humidity in the Air. Observed instantaneous relative humidity (water vapour in air)',
    )
    temperature: Optional[float] = Field(None, description='Temperature of the item')


class DayMinimum(BaseModel):
    feelLikesTemperature: Optional[float] = Field(
        None, description='Temperature appreciation of the item'
    )
    relativeHumidity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description='Humidity in the Air. Observed instantaneous relative humidity (water vapour in air)',
    )
    temperature: Optional[float] = Field(None, description='Temperature of the item')


class Type7(Enum):
    Point = 'Point'


class Location6(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[float] = Field(..., min_length=2)
    type: Type7


class Type8(Enum):
    LineString = 'LineString'


class Location7(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[Coordinate] = Field(..., min_length=2)
    type: Type8


class Type9(Enum):
    Polygon = 'Polygon'


class Location8(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[Coordinate]]
    type: Type9


class Type10(Enum):
    MultiPoint = 'MultiPoint'


class Location9(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[float]]
    type: Type10


class Type11(Enum):
    MultiLineString = 'MultiLineString'


class Location10(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[Coordinate]]
    type: Type11


class Type12(Enum):
    MultiPolygon = 'MultiPolygon'


class Location11(BaseModel):
    bbox: Optional[List[float]] = Field(None, min_length=4)
    coordinates: List[List[List[Coordinate]]]
    type: Type12


class Type13(Enum):
    WeatherForecast = 'WeatherForecast'


class WeatherForecast(BaseModel):
    address: Optional[Address] = Field(None, description='The mailing address')
    agriparcel: Optional[Any] = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    alternateName: Optional[str] = Field(
        None, description='An alternative name for this item'
    )
    areaServed: Optional[str] = Field(
        None,
        description='The geographic area where a service or offered item is provided',
    )
    atmosphericPressure: Optional[confloat(ge=0.0)] = Field(
        None, description='The atmospheric pressure observed measured in Hecto Pascals'
    )
    dataProvider: Optional[str] = Field(
        None,
        description='A sequence of characters identifying the provider of the harmonised data entity',
    )
    dateCreated: Optional[AwareDatetime] = Field(
        None,
        description='Entity creation timestamp. This will usually be allocated by the storage platform',
    )
    dateIssued: AwareDatetime = Field(
        ...,
        description='The date and time the forecast was issued by the meteorological bureau in ISO8601 UTC format',
    )
    dateModified: Optional[AwareDatetime] = Field(
        None,
        description='Timestamp of the last modification of the entity. This will usually be allocated by the storage platform',
    )
    dateRetrieved: Optional[AwareDatetime] = Field(
        None,
        description='The date and time the forecast was retrieved in ISO8601 UTC format',
    )
    dayMaximum: Optional[DayMaximum] = Field(
        None,
        description='Maximum values for the reported period. Subattributes:- `temperature` : Maximum temperature. See `WeatherForecast.temperature` for description and units. - `feelLikesTemperature`. Maximum feels like temperature. Same semantics and units as `WeatherForecast.feelsLikeTemperature`.-   `relativeHumidity`. Maximum relative humidity. Same semantics and units as `WeatherForecast.relativeHumidity`',
    )
    dayMinimum: Optional[DayMinimum] = Field(
        None,
        description='Minimum values forecasted for the reported period.  Minimum values for the reported period. Subattributes:- `temperature` : Minimum temperature. See `WeatherForecast.temperature` for description and units. - `feelLikesTemperature`. Minimum feels like temperature. Same semantics and units as `WeatherForecast.feelsLikeTemperature`.- `relativeHumidity`. Minimum relative humidity. Same semantics and units as `WeatherForecast.relativeHumidity`',
    )
    description: Optional[str] = Field(None, description='A description of this item')
    feelsLikeTemperature: Optional[float] = Field(
        None, description='Temperature appreciation of the item'
    )
    gustSpeed: Optional[float] = Field(
        None,
        description='A sudden burst of high-speed wind over the observed average wind speed lasting only for a few seconds',
    )
    id: Union[
        constr(
            pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$', min_length=1, max_length=256
        ),
        AnyUrl,
    ] = Field(..., description='Unique identifier of the entity')
    illuminance: Optional[confloat(ge=0.0)] = Field(
        None,
        description='(https://en.wikipedia.org/wiki/Illuminance) observed measured in lux (lx) or lumens per square metre (cd·sr·m−2)',
    )
    location: Optional[
        Union[Location6, Location7, Location8, Location9, Location10, Location11]
    ] = Field(
        None,
        description='Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon',
    )
    name: Optional[str] = Field(None, description='The name of this item')
    owner: Optional[
        List[
            Union[
                constr(
                    pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$',
                    min_length=1,
                    max_length=256,
                ),
                AnyUrl,
            ]
        ]
    ] = Field(
        None,
        description='A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)',
    )
    precipitation: Optional[confloat(ge=0.0)] = Field(
        None, description='Amount of water rain expected'
    )
    precipitationProbability: Optional[confloat(ge=0.0)] = Field(
        None, description='Probability of rainfall.'
    )
    refPointOfInterest: Optional[str] = Field(
        None, description='Point of interest related to the item'
    )
    relativeHumidity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description='Humidity in the Air. Observed instantaneous relative humidity (water vapour in air)',
    )
    seeAlso: Optional[Union[List[AnyUrl], AnyUrl]] = Field(
        None, description='list of uri pointing to additional resources about the item'
    )
    source: Optional[str] = Field(
        None,
        description='A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object',
    )
    temperature: Optional[float] = Field(None, description='Temperature of the item')
    type: Type13 = Field(
        ..., description='NGSI Entity type. It has to be WeatherForecast'
    )
    validFrom: Optional[AwareDatetime] = Field(
        None, description='Validity period start date and time'
    )
    validTo: Optional[AwareDatetime] = Field(
        None, description='Validity period end date and time'
    )
    validity: Optional[str] = Field(
        None,
        description='Includes the validity period for this forecast as a ISO8601 time interval. As a workaround for the lack of support of Orion Context Broker for datetime intervals, it can be used two separate attributes: `validFrom`, `validTo`',
    )
    weatherType: Optional[str] = Field(
        None, description='Text description of the weather'
    )
    windDirection: Optional[confloat(ge=0.0, le=360.0)] = Field(
        None, description='Direction of the wind bet'
    )
    windSpeed: Optional[confloat(ge=0.0)] = Field(
        None, description='Intensity of the wind'
    )
