# generated by datamodel-codegen:
#   filename:  models.yaml
#   timestamp: 2026-08-06T11:50:21+00:00

from __future__ import annotations

from datetime import date as date_aliased
from typing import Any

from pydantic import BaseModel, Field, confloat


class FertilizerApplication(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    application_depth_fert: Any | None = Field(
        None,
        description='Fertilizer application depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#fedep'}},
    )
    ca_in_applied_fertilizer: Any | None = Field(
        None,
        description='Ca in applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feamc'}},
    )
    category: Any | None = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Any | None = Field(
        None, description='Date when the operation was executed'
    )
    fertiliz_app_name: Any | None = Field(
        None,
        description='Name or notes for this fertilizer application',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#fecd_name'}
        },
    )
    fertiliz_code_other_elem: Any | None = Field(
        None,
        description='Fertilizer code for other elements (e.g., Mg for magnesium)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feocd'}},
    )
    fertilization_date: date_aliased = Field(
        ...,
        description='Fertilization date',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#fedate'}
        },
    )
    fertilizer_applic_day: Any | None = Field(
        None,
        description='Fertilizer application day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feday'}},
    )
    fertilizer_applic_method: Any | None = Field(
        None,
        description='Fertilizer application method',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feacd'}},
    )
    fertilizer_applic_year: Any | None = Field(
        None,
        description='Fertilizer application year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feyr'}},
    )
    fertilizer_k_applied: Any | None = Field(
        None,
        description='Potassium in applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feamk'}},
    )
    fertilizer_level: Any | None = Field(
        None,
        description='Fertilizer level in treatment structure',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#fe'}},
    )
    fertilizer_material: Any | None = Field(
        None,
        description='Fertilizer material',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#fecd'}},
    )
    id: Any = Field(..., description='nglsi-id id')
    n_in_applied_fertilizer: float = Field(
        ...,
        description='Nitrogen in applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feamn'}},
    )
    nh4_applied_fertilizer: Any | None = Field(
        None,
        description='Ammonium in applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#fenh4'}},
    )
    no3_applied_fertilizer: Any | None = Field(
        None,
        description='Nitrate applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feno3'}},
    )
    other_elements_appl_fert: Any | None = Field(
        None,
        description='Other elements in applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feamo'}},
    )
    phosphorus_applied_fert: Any | None = Field(
        None,
        description='Phosphorus in applied fertilizer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#feamp'}},
    )
    spatial_category: Any | None = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be FertilizerApplication')


class HarvestEvent(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Any | None = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Any | None = Field(
        None, description='Date when the operation was executed'
    )
    harv_operat_main_product: Any | None = Field(
        None,
        description='Harvest operations, percent economic product harvested',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#happc'}},
    )
    harv_operat_size_categor: Any | None = Field(
        None,
        description='Harvest operations size category',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hasiz'}},
    )
    harv_operation_byproduct: Any | None = Field(
        None,
        description='Harvest operations, percent of by-product harvested',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#habpc'}},
    )
    harvest_amount: float = Field(
        ...,
        description='Harvest, total amount removed as mass',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hamt'}},
    )
    harvest_area: Any | None = Field(
        None,
        description='Harvest area',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#harea'}},
    )
    harvest_crop: Any | None = Field(
        None,
        description='Harvest operations, crop harvested',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hacr'}},
    )
    harvest_cut_height: Any | None = Field(
        None,
        description='Harvest, height of cut',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#haht'}},
    )
    harvest_method: Any | None = Field(
        None,
        description='Harvest method',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#harm'}},
    )
    harvest_operat_component: Any | None = Field(
        None,
        description='Harvest operations, crop component harvested',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hacom'}},
    )
    harvest_operations_date: date_aliased = Field(
        ...,
        description='Harvest operations date, DAP if year = -99',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hadat'}},
    )
    harvest_operations_day: Any | None = Field(
        None,
        description='Harvest operations day, DAP if year = -99',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#haday'}},
    )
    harvest_operations_level: Any | None = Field(
        None,
        description='Harvest operations level, links to HARVEST table',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ha'}},
    )
    harvest_operations_year: Any | None = Field(
        None,
        description='Harvest operations year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hayr'}},
    )
    harvest_stage: Any | None = Field(
        None,
        description='Harvest, growth stage of crop at date',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#hastg'}},
    )
    id: Any = Field(..., description='nglsi-id id')
    spatial_category: Any | None = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be HarvestEvent')


class IrrigationApplication(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    bund_height: Any | None = Field(
        None,
        description='Bund height (e.g., for flooded rice)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#abund'}},
    )
    category: Any | None = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Any | None = Field(
        None, description='Date when the operation was executed'
    )
    id: Any = Field(..., description='nglsi-id id')
    irrig_amount_depth: Any | None = Field(
        None,
        description='Irrigation amount, depth of water',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#irval'}},
    )
    irrigation_applic_depth: Any | None = Field(
        None,
        description='Irrigation application depth (e.g., for depth to drip line)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#iradp'}},
    )
    irrigation_date: date_aliased = Field(
        ...,
        description='Irrigation date',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#idate'}},
    )
    irrigation_day: Any | None = Field(
        None,
        description='Irrigation day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#irday'}},
    )
    irrigation_h2o_n_conc: Any | None = Field(
        None,
        description='Irrigation water nitrogen concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#irnpc'}},
    )
    irrigation_level: Any | None = Field(
        None,
        description='Irrigation level, links to IRRIGATIONS table',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ir'}},
    )
    irrigation_operation: Any | None = Field(
        None,
        description='Irrigation operation (e.g., furrow, sprinkler, drip…)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#irop'}},
    )
    irrigation_operation_name: Any | None = Field(
        None,
        description='Name of irrigation operation or specific notes about this application',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#irop_name'}
        },
    )
    irrigation_year: Any | None = Field(
        None,
        description='Irrigation or water management year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#iryr'}},
    )
    spatial_category: Any | None = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be IrrigationApplication')


class OrganicMaterialApplication(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Any | None = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Any | None = Field(
        None, description='Date when the operation was executed'
    )
    id: Any = Field(..., description='nglsi-id id')
    org_material_appl_depth: Any | None = Field(
        None,
        description='Organic materials application depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omdep'}},
    )
    org_material_applic_amnt: float = Field(
        ...,
        description='Organic materials application amount, dry weight basis',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omamt'}},
    )
    org_material_applic_date: date_aliased = Field(
        ...,
        description='Organic materials application date',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omdat'}},
    )
    org_material_applic_day: Any | None = Field(
        None,
        description='Organic materials application day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omday'}},
    )
    org_material_applic_meth: Any | None = Field(
        None,
        description='Organic materials application method',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omacd'}},
    )
    org_material_c_to_n: float = Field(
        ...,
        description='Organic materials C:N ratio',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omc2n'}},
    )
    org_material_cover: Any | None = Field(
        None,
        description='Organic materials, percent ground covered by organic matter',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omcov'}},
    )
    org_material_incorp_perc: Any | None = Field(
        None,
        description='Organic materials application, fraction incorporporated as %',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ominp'}},
    )
    org_material_lignin_conc: Any | None = Field(
        None,
        description='Organic materials lignin concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omlpc'}},
    )
    org_materials_applic_lev: Any | None = Field(
        None,
        description='Organic materials application level, links to OM table',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#om'}},
    )
    org_materials_applic_yr: Any | None = Field(
        None,
        description='Organic materials application year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omyr'}},
    )
    org_matter_carbon_conc: Any | None = Field(
        None,
        description='Organic matter or residue added, carbon concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omcpc'}},
    )
    org_matter_moisture_conc: Any | None = Field(
        None,
        description='Organic matter or residue added, moisture concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omh2o'}},
    )
    organic_material: str = Field(
        ...,
        description='Organic material, identifying code',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omcd'}},
    )
    organic_material_k_conc: Any | None = Field(
        None,
        description='Organic materials potasium concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omkpc'}},
    )
    organic_material_n_conc: float = Field(
        ...,
        description='Organic materials nitrogen concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omnpc'}},
    )
    organic_material_p_conc: Any | None = Field(
        None,
        description='Organic materials phosphorus concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#omppc'}},
    )
    spatial_category: Any | None = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    type: Any = Field(
        ..., description='nglsi-id type, has to be OrganicMaterialApplication'
    )


class Planting(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Any | None = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    crop_code: Any | None = Field(None, description='ICASA crop code')
    crop_common_name: str = Field(..., description='ICASA crop common name')
    cultivar_name: str = Field(..., description='ICASA cultivar name')
    dateObserved: Any | None = Field(
        None, description='Date when the operation was executed'
    )
    emergence_date: Any | None = Field(
        None,
        description='Date of emergence',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#edate'}},
    )
    emergence_day: Any | None = Field(
        None,
        description='Day of year for date of emergence',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#pldoe'}},
    )
    emergence_year: Any | None = Field(
        None,
        description='Year for date of emergence (growth stage)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plyre'}},
    )
    fertile_tiller_num: Any | None = Field(
        None,
        description='Fertile tiller number (sorghum)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plftn'}},
    )
    germination: Any | None = Field(
        None,
        description='Planting material germination',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plgpc'}},
    )
    id: Any = Field(..., description='nglsi-id id')
    length_sprout_material: Any | None = Field(
        None,
        description='Planting material sprout length',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plspl'}},
    )
    nursery_env_pl_material: Any | None = Field(
        None,
        description='Transplant nursery environment (mean temperature)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plenv'}},
    )
    plant_pop_at_emergence: Any | None = Field(
        None,
        description='Plant population at emergence',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plpoe'}},
    )
    plant_pop_at_planting: Any | None = Field(
        None,
        description='Plant population at planting',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plpop'}},
    )
    planting_date: date_aliased = Field(
        ...,
        description='Planting or sowing date',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#pdate'}},
    )
    planting_day: Any | None = Field(
        None,
        description='Day of planting',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plday'}},
    )
    planting_depth: Any | None = Field(
        None,
        description='Planting depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#pldp'}},
    )
    planting_distribution: Any | None = Field(
        None,
        description='Planting distribution',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plds'}},
    )
    planting_level: Any | None = Field(
        None,
        description='Planting, level in treatment structure',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#pl'}},
    )
    planting_level_name: Any | None = Field(
        None,
        description='Planting level, name of treatment',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#pl_name'}
        },
    )
    planting_material: Any | None = Field(
        None,
        description='Planting material',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plma'}},
    )
    planting_material_age: Any | None = Field(
        None,
        description='Planting material age (also used for dormancy adjustments)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plage'}},
    )
    planting_material_source: Any | None = Field(
        None,
        description='Source of the planting material',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#plmsource'}
        },
    )
    planting_material_weight: Any | None = Field(
        None,
        description='Planting material weight',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plmwt'}},
    )
    planting_year: Any | None = Field(
        None,
        description='Planting year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plyr'}},
    )
    plants_per_hill: Any | None = Field(
        None,
        description='Plants per hill',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plph'}},
    )
    row_direction: Any | None = Field(
        None,
        description='Row direction, degrees from N',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plrd'}},
    )
    row_spacing: Any | None = Field(
        None,
        description='Row spacing',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#plrs'}},
    )
    seedbed_density: Any | None = Field(
        None,
        description='Planting density in nursery seed bed',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#nplsb'}},
    )
    spatial_category: Any | None = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    transplant_age: Any | None = Field(
        None,
        description='Transplant age',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#page'}},
    )
    transplant_date: Any | None = Field(
        None,
        description='Transplant date',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#trdate'}
        },
    )
    type: Any = Field(..., description='nglsi-id type, has to be Planting')


class TillageEvent(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    category: Any | None = Field(
        None,
        description='Constant `ManagementActivity` used for querying all operations',
    )
    dateObserved: Any | None = Field(
        None, description='Date when the operation was executed'
    )
    id: Any = Field(..., description='nglsi-id id')
    spatial_category: Any | None = Field(
        None,
        description='Category of the management activity and related agriparcel. Same management activity is created as both spatial_category h3 and growthfield entities. So duplicates of the activities exist, activities have to be fetched per spatial_category.',
    )
    till_mix_effectiveness: Any | None = Field(
        None,
        description='Tillage operations mixing effectiveness',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#timix'}},
    )
    tillage_date: date_aliased = Field(
        ...,
        description='Tillage date',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tdate'}},
    )
    tillage_implement: Any | None = Field(
        None,
        description='Tillage implement',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tiimp'}},
    )
    tillage_level: Any | None = Field(
        None,
        description='Tillage operation level',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ti'}},
    )
    tillage_operation_name: str = Field(
        ...,
        description='Tillage operations, name of specific event',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#ti_op_name'}
        },
    )
    tillage_operations_day: Any | None = Field(
        None,
        description='Tillage operations day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tiday'}},
    )
    tillage_operations_depth: Any | None = Field(
        None,
        description='Tillage operations depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tidep'}},
    )
    tillage_operations_year: Any | None = Field(
        None,
        description='Tillage operations year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tiyr'}},
    )
    tillage_order: Any | None = Field(
        None,
        description='Tillage operations order within a single day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tiord'}},
    )
    type: Any = Field(..., description='nglsi-id type, has to be TillageEvent')


class Genotype(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    crop_ident_icasa: Any | None = Field(
        None,
        description='Crop (or weed) species identifier',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#crid'}},
    )
    cultivar_identifier: Any | None = Field(
        None,
        description='Cultivar, line or genotype identifier',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#cul_id'}
        },
    )
    cultivar_name: Any | None = Field(
        None,
        description='Cultivar name',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#cul_name'}
        },
    )
    cultivar_notes: Any | None = Field(
        None,
        description='Cultivar notes',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#cul_notes'}
        },
    )
    genotype_level_number: Any | None = Field(
        None,
        description='Genotype level, as listed in Treatments table under GE',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ge'}},
    )
    id: Any | None = Field(
        None,
        description='id',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#id'}},
    )
    relative_maturity: Any | None = Field(
        None,
        description='Relative maturity',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#rm'}},
    )
    type: Any = Field(..., description='nglsi-id type, has to be Genotype')


class InitialCondition(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    day_year_residue_measure: Any | None = Field(
        None,
        description='Day of year, residue measurement',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrdy'}},
    )
    id: Any | None = Field(
        None,
        description='id',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#id'}},
    )
    init_residu_measure_date: Any | None = Field(
        None,
        description='Initial residues measurement date',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#icrdat'}
        },
    )
    init_residue_measure_yr: Any | None = Field(
        None,
        description='Initial residues measurement year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icryr'}},
    )
    initial_co2: Any | None = Field(None, description='Initial atmospheric CO2 level')
    initial_conditions_date: Any | None = Field(
        None,
        description='Initial conditions measurement date',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icdat'}},
    )
    initial_conditions_level: Any | None = Field(
        None,
        description='Initial conditions level, link',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ic'}},
    )
    initial_conditions_name: Any | None = Field(
        None,
        description='Initial conditions name',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#ic_name'}
        },
    )
    initial_prof_inorg_n: Any | None = Field(
        None,
        description='Initial profile inorganic nitrogen amount',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icin'}},
    )
    initial_prof_measure_yr: Any | None = Field(
        None,
        description='Inital profile measurements year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icyr'}},
    )
    initial_prof_nh4: Any | None = Field(
        None,
        description='Initial profile soil ammonium',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#icpnh4'}
        },
    )
    initial_prof_no3: Any | None = Field(
        None,
        description='Initial profile soil nitrate',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#icpno3'}
        },
    )
    initial_profile_wtr_cont: Any | None = Field(
        None,
        description='Initial water content of entire profile',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icsw'}},
    )
    initial_profile_wtr_cont__: Any | None = Field(
        None,
        alias='initial_profile_wtr_cont_%',
        description='Initial water content of entire profile, expressed as percent of available water',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#icswpc'}
        },
    )
    initial_water_tabl_depth: Any | None = Field(
        None,
        description='Initial water table depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icwt'}},
    )
    nodule_wt_previous_crop: Any | None = Field(
        None,
        description='Nodule weight from previous crop',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icnd'}},
    )
    profile_measurement_day: Any | None = Field(
        None,
        description='Day of year, inital profile measurement',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icday'}},
    )
    residue_above_ground_wt: Any | None = Field(
        None,
        description='Residue above-ground weight, dry weight basis',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrag'}},
    )
    residue_incorpor_depth: Any | None = Field(
        None,
        description='Residue incorporation depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrdp'}},
    )
    residue_incorporated: Any | None = Field(
        None,
        description='Residue incorporation percentage',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrip'}},
    )
    residue_k_conc: Any | None = Field(
        None,
        description='Residue, above-ground, potassium concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrk'}},
    )
    residue_lignin_conc: Any | None = Field(
        None,
        description='Residue, above-ground, lignin concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrli'}},
    )
    residue_moisture_init: Any | None = Field(
        None,
        description='Moisture in initial above-ground residue ',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrm'}},
    )
    residue_n_conc: Any | None = Field(
        None,
        description='Residue, above-ground, nitrogen concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrn'}},
    )
    residue_nature_prev_crop: Any | None = Field(
        None,
        description='Residue, crop code for previous crop',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icpcr'}},
    )
    residue_p_conc: Any | None = Field(
        None,
        description='Residue, above-ground, phosphorus concentration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrp'}},
    )
    rhizobia_effectiveness: Any | None = Field(
        None,
        description='Rhizobia effectiveness on 0-1 scale',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrze'}},
    )
    rhizobia_nitrogen_amount: Any | None = Field(
        None,
        description='Rhizobia nitrogen amount',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrzn'}},
    )
    rhizobia_number: Any | None = Field(
        None,
        description='Rhizobia number (count)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrzc'}},
    )
    root_wt_previous_crop: Any | None = Field(
        None,
        description='Root weight from previous crop',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#icrt'}},
    )
    type: Any = Field(..., description='nglsi-id type, has to be InitialCondition')


class Soil(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    distrib_restrictions: Any | None = Field(
        None,
        description='Distribution limitations for the soils data set',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_distrib'}
        },
    )
    file_version_sl: Any | None = Field(
        None,
        description='File version for ICASA standard',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#version_sl'}
        },
    )
    id: Any = Field(..., description='nglsi-id id')
    revision_date_first_sl: Any | None = Field(
        None,
        description='Date the file was first created',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#rev_date_first_sl'}
        },
    )
    revision_date_latest_sl: Any | None = Field(
        None,
        description='Date the file was last modified',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#rev_date_latest_sl'}
        },
    )
    revision_notes_sl: Any | None = Field(
        None,
        description='Notes describing reasons for the revision',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#revision_notes_sl'}
        },
    )
    soil_citation: Any | None = Field(
        None,
        description='Full citation for soil data',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_citation'}
        },
    )
    soil_license: Any | None = Field(
        None,
        description='License associated with soil data',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_license'}
        },
    )
    soil_notes: Any | None = Field(
        None,
        description='Notes describing soil dataset',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_notes'}
        },
    )
    soil_profile_methods: Any | None = Field(
        None,
        description='General notes on execution of experiment.',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#methods'}
        },
    )
    type: Any = Field(..., description='nglsi-id type, has to be Soil')


class SoilProfile(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    cona: Any | None = Field(
        None,
        description='Apsim Cona soil evaporation ',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#cona'}},
    )
    depth_of_topsoil: Any | None = Field(
        None,
        description='Thickness of topsoil',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sltop'}},
    )
    diffus_const: Any | None = Field(
        None,
        description='APSIM Evaporative diffusion constant',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#diffusconst'}
        },
    )
    diffus_slope: Any | None = Field(
        None,
        description='APSIM Evaporative diffusion slope',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#diffusslope'}
        },
    )
    drainage_rate_per_day: Any | None = Field(
        None,
        description='Drainage rate as fraction per day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sldr'}},
    )
    electric_conductivity: Any | None = Field(
        None, description='Electric conductivity, in siemens'
    )
    grid_id: Any | None = Field(
        None, description='Id of the cell on the chosen grid, e.g. h3 grid id'
    )
    id: Any = Field(..., description='nglsi-id id')
    latitude_soil_profile: Any | None = Field(
        None,
        description='Latitude of soil profile site',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_lat'}
        },
    )
    longitude_soil_profile: Any | None = Field(
        None,
        description='Longitude of soil profile site',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_long'}
        },
    )
    mineralization_factor: Any | None = Field(
        None,
        description='Mineralization factor (0 to 1 scale)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slnf'}},
    )
    name_of_soil_profile: Any | None = Field(
        None,
        description='Name of soil profile',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_name'}
        },
    )
    ph_buffer_determin_meth: Any | None = Field(
        None,
        description='pH in buffer determination method',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#smhb'}},
    )
    phosphorus_determ_method: Any | None = Field(
        None,
        description='Phosphorus determination method',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#smpx'}},
    )
    potassium_determ_method: Any | None = Field(
        None,
        description='Potassium determination method',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#smke'}},
    )
    runoff_curve_no_scs: Any | None = Field(
        None,
        description='Runoff curve no. (Soil Conservation Service)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slro'}},
    )
    soil_albedo: Any | None = Field(
        None,
        description='Soil albedo, dry soil',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#salb'}},
    )
    soil_albedo_moist: Any | None = Field(
        None,
        description='Soil albedo, moist soil',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#salbm'}},
    )
    soil_classific_system: Any | None = Field(
        None,
        description='Soil classification system (e.g., FAO, USDA)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_system'}
        },
    )
    soil_classification: Any | None = Field(
        None,
        description='Soil classification',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#classification'}
        },
    )
    soil_denitrification_fac: Any | None = Field(
        None,
        description='Soil denitrification factor',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sldn'}},
    )
    soil_depth: Any | None = Field(
        None,
        description='Soil depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sldp'}},
    )
    soil_evaporation_limit: Any | None = Field(
        None,
        description='Soil evaporation, upper limit for stage 1',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slu1'}},
    )
    soil_fertility_on_photo: Any | None = Field(
        None,
        description='Soil fertility effect on photosynthesis (0 to 1 scale)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slpf'}},
    )
    soil_file_id: Any | None = Field(
        None,
        description='Soil profile file name',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_file_id'}
        },
    )
    soil_id: Any | None = Field(
        None,
        description='Unique soil identifier linking to SOIL_PROFILES',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sid'}},
    )
    soil_loc_2nd_level: Any | None = Field(
        None,
        description='Second admin level for location of site for soil profile (usually state or province)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_loc_2'}
        },
    )
    soil_loc_3rd_level: Any | None = Field(
        None,
        description='Third admin level for location of site for soil profile (usually county or municipality)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_loc_3'}
        },
    )
    soil_location_country: Any | None = Field(
        None,
        description='First admin for location of site for soil profile (usually country)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_loc_1'}
        },
    )
    soil_profile_id: Any | None = Field(
        None,
        description='Soil profile identifier',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_id'}
        },
    )
    soil_profile_slope: Any | None = Field(
        None,
        description='Slope where soil profile characterized',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#sl_slope'}
        },
    )
    soil_site: Any | None = Field(
        None,
        description='Name of site where soil profile data sampled',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_site'}
        },
    )
    soil_site_elevation: Any | None = Field(
        None,
        description='Elevation of soil profile site',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_elev'}
        },
    )
    soil_surface_color: Any | None = Field(
        None,
        description='Surface soil color, moist, using Munsell hue',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sscol'}},
    )
    soil_texture: Any | None = Field(
        None,
        description='Soil texture',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sltx'}},
    )
    spatial_category: Any | None = Field(
        None,
        description='Category of the soil profile layer and related agriparcel. Same soil profile layer is created as both spatial_category h3 and basefield entities.So duplicates of the soil profile layers exist, soil profile layers have to be fetched per spatial_category.',
    )
    summer_u: Any | None = Field(
        None,
        description='Summer soil evaporation, upper limit for stage 1',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#summeru'}
        },
    )
    surface_stones__cover_: Any | None = Field(
        None,
        alias='surface_stones_(cover)',
        description='Surface stones (cover)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#flst'}},
    )
    type: Any = Field(..., description='nglsi-id type, has to be SoilProfile')
    winter_u: Any | None = Field(
        None,
        description='Winter soil evaporation, upper limit for stage 1',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#winteru'}
        },
    )


class SoilProfileLayer(BaseModel):
    agriparcel: str | None = Field(None, description='Reference to the AgriParcel')
    caco3_content: Any | None = Field(
        None,
        description='Soil CaCO3 content',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#caco3'}},
    )
    cation_exchange_capacity: Any | None = Field(
        None,
        description='Cation exchange capacity',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slcec'}},
    )
    date: Any | None = Field(None, description='Date of observation')
    electric_conductivity: Any | None = Field(
        None,
        description='Electric conductivity',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slec'}},
    )
    grid_id: Any | None = Field(
        None, description='Id of the cell on the chosen grid, e.g. h3 grid id'
    )
    id: Any = Field(..., description='nglsi-id id')
    iron: Any | None = Field(
        None,
        description='Iron',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slfe'}},
    )
    layer_drainage_rate_per_day: Any | None = Field(
        None,
        description='Drainage rate as fraction per day, per layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sldrl'}},
    )
    master_horizon: Any | None = Field(
        None,
        description='Master horizon',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slmh'}},
    )
    nh4soil_kcl: Any | None = Field(
        None,
        description='NH4 in soil based on KCl extraction, by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#snh4'}},
    )
    nitrate_kcl: Any | None = Field(
        None,
        description='Nitrate in soil based on KCl extraction, by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sno3'}},
    )
    phosphorus_extractable: Any | None = Field(
        None,
        description='Phosphorus, extractable',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slpx'}},
    )
    phosphorus_iostherm_b: Any | None = Field(
        None,
        description='Phosphorus iostherm B',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slpb'}},
    )
    phosphorus_isotherm_a: Any | None = Field(
        None,
        description='Phosphorus isotherm A',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slpa'}},
    )
    phosphorus_organic: Any | None = Field(
        None,
        description='Phosphorus, organic',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slpo'}},
    )
    phosphorus_total: Any | None = Field(
        None,
        description='Phosphorus, total',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slpt'}},
    )
    plant_root_uptake_factor: Any | None = Field(
        None,
        description='APSIM plant specific water uptake coefficient',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#apsim_kl'}
        },
    )
    potassium_exchangeable: Any | None = Field(
        None,
        description='Potassium, exchangeable',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slke'}},
    )
    root_growth_factor_soil: Any | None = Field(
        None,
        description='Root growth factor, soil only (0 to 1 scale)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slrgf'}},
    )
    sat_hydraul_conductivity: Any | None = Field(
        None,
        description='Saturated hydraulic conductivity',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sksat'}},
    )
    soil_active_c: Any | None = Field(
        None,
        description='Biologically active soil organic carbon by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slacc'}},
    )
    soil_active_c_fraction: Any | None = Field(
        None,
        description='Biologically active soil organic carbon by layer, fraction of total organic C',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slfac'}},
    )
    soil_adsorption_coef: Any | None = Field(
        None,
        description='Soil adsorption coefficient (0 to 1 scale)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sladc'}},
    )
    soil_aluminum_conc: Any | None = Field(
        None,
        description='Soil aluminum concentration in profile described',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slal'}},
    )
    soil_base_saturation: Any | None = Field(
        None,
        description='Soil base saturation',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slbs'}},
    )
    soil_bulk_density_moist: Any | None = Field(
        None,
        description='Soil bulk density when moist for layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slbdm'}},
    )
    soil_c_to_n_ratio: Any | None = Field(
        None,
        description='Initial C:N ratio of organic matter, C kg/N kg, definition from WOFOST',
    )
    soil_calcium_conc: Any | None = Field(
        None,
        description='Soil calcium, exchangeable',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slca'}},
    )
    soil_clay_fraction: float | None = Field(
        None,
        description='Soil texture, clay (<0.002 mm), weight percent of fine earth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slcly'}},
    )
    soil_coarse_fraction: Any | None = Field(
        None,
        description='Soil texture, coarse fraction (>2 mm), weight percent of fine earth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slcf'}},
    )
    soil_color_moist_munsell: Any | None = Field(
        None,
        description='Soil color of moist soil using Munsell hue',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slcom'}},
    )
    soil_compac_fact_by_lyr: Any | None = Field(
        None,
        description='Soil compaction factor by layer (0 to 1 scale)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#scmpf'}},
    )
    soil_critical_air_content_for_roots: Any | None = Field(
        None,
        description='Critical air content for roots, air m3/ soil m3, definition from WOFOST',
    )
    soil_file_id: Any | None = Field(
        None,
        description='Soil profile file name',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_file_id'}
        },
    )
    soil_id: Any | None = Field(
        None,
        description='Unique soil identifier linking to SOIL_PROFILES',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sid'}},
    )
    soil_inert_c: Any | None = Field(
        None,
        description='Inert organic carbon by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slic'}},
    )
    soil_inert_c_fraction: Any | None = Field(
        None,
        description='Inert organic carbon by layer, fraction of total organic C',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slfic'}},
    )
    soil_intermediate_c: Any | None = Field(
        None,
        description='Intermediate soil organic carbon by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slinc'}},
    )
    soil_intermediate_c_fraction: Any | None = Field(
        None,
        description='Intermediate soil organic carbon by layer, fraction of total organic C',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#slfinc'}
        },
    )
    soil_layer_base_depth: float | None = Field(
        None,
        description='Soil layer base depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sllb'}},
    )
    soil_layer_top_depth: float | None = Field(
        None,
        description='Soil layer top depth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sllt'}},
    )
    soil_magnesium_conc: Any | None = Field(
        None,
        description='Magnesium',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slmg'}},
    )
    soil_manganese_conc: Any | None = Field(
        None,
        description='Manganese',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slmn'}},
    )
    soil_organic_c_perc_layr: float | None = Field(
        None,
        description='Total soil organic carbon by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sloc'}},
    )
    soil_organic_matter_perc_layer: Any | None = Field(
        None, description='Soil organic matter per layer, OM kg/ soil kg'
    )
    soil_organic_n_conc: Any | None = Field(
        None,
        description='Nitrogen, total soil organic',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slni'}},
    )
    soil_ph_in_buffer: Any | None = Field(
        None,
        description='pH of soil measured in buffer solution, from profile description',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slphb'}},
    )
    soil_ph_in_water: Any | None = Field(
        None,
        description='pH of soil in water, from profile description',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slphw'}},
    )
    soil_profile_id: Any | None = Field(
        None,
        description='Soil profile identifier',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#soil_id'}
        },
    )
    soil_sand_fraction: float | None = Field(
        None,
        description='Soil texture, sand (0.05 to 2.0 mm), weight percent of fine earth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slsnd'}},
    )
    soil_silt_fraction: float | None = Field(
        None,
        description='Soil texture, silt (0.05 to 0.002 mm), weight percent of fine earth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slsil'}},
    )
    soil_sodium_conc: Any | None = Field(
        None,
        description='Sodium in soil layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slna'}},
    )
    soil_stable_c: Any | None = Field(
        None,
        description='Stable organic carbon by layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slsc'}},
    )
    soil_stable_c_fraction: Any | None = Field(
        None,
        description='Stable organic carbon by layer, fraction of total organic C',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slfsc'}},
    )
    soil_sulphur_conc: Any | None = Field(
        None,
        description='Sulphur in soil layer',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slsu'}},
    )
    soil_type: Any | None = Field(None, description='Finnish soil type')
    soil_wat_drned_upper_lim: Any | None = Field(
        None,
        description='Soil water, drained upper limit',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sldul'}},
    )
    soil_water_air_dry: Any | None = Field(
        None,
        description='Soil water content, air dry',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sladr'}},
    )
    soil_water_field_cap_1: float | None = Field(
        None,
        description='Soil water content at 1/3 atmosphere pressure',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slfc1'}},
    )
    soil_water_field_cap_2: float | None = Field(
        None,
        description='Soil water content at 1/10 atmospheric pressure',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slfc2'}},
    )
    soil_water_lower_limit: Any | None = Field(
        None,
        description='Soil water, lower limit',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slll'}},
    )
    soil_water_residual: Any | None = Field(
        None,
        description='Soil water, residual',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slres'}},
    )
    soil_water_saturated: float | None = Field(
        None,
        description='Soil water, saturated',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slsat'}},
    )
    soil_water_uptake_factor: Any | None = Field(
        None,
        description='Root exploration factor (0 to 1 scale, APSIM XF)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slxf'}},
    )
    soil_water_wilting_pt: float | None = Field(
        None,
        description='Soil water content (wilting point) at 15 atmosphere pressure ',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#slwp'}},
    )
    spatial_category: Any | None = Field(
        None,
        description='Category of the soil profile layer and related agriparcel. Same soil profile layer is created as both spatial_category h3 and basefield entities.So duplicates of the soil profile layers exist, soil profile layers have to be fetched per spatial_category.',
    )
    type: Any = Field(..., description='nglsi-id type, has to be SoilProfileLayer')
    van_genuch_alpha: Any | None = Field(
        None,
        description='Van Genuchten alpha parameter',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#vg_alpha'}
        },
    )
    van_genuch_n: Any | None = Field(
        None,
        description='Van Genuchten N parameter',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#vg_n'}},
    )
    year: Any | None = Field(None, description='Year of observation')


class WeatherStation(BaseModel):
    field_psychrometric_constant_: Any | None = Field(
        None,
        alias=' psychrometric_constant ',
        description=' Psychrometric constant ',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#psycon'}
        },
    )
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    angstrom_coef_a_year: Any | None = Field(
        None,
        description='Angstrom A coefficient, yearly',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#anga'}},
    )
    angstrom_coef_b_year: Any | None = Field(
        None,
        description='Angstrom B coefficient, yearly',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#angb'}},
    )
    co2_conc_annual_increase: Any | None = Field(
        None,
        description='CO2 concentration, annual increase ',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#co2a'}},
    )
    co2_concentration_annual: Any | None = Field(
        None,
        description='CO2 concentration, annual (yearly)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#co2y'}},
    )
    durat_summarization_per: Any | None = Field(
        None,
        description='Duration of summarization period',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#durn'}},
    )
    e_mail_address: Any | None = Field(
        None, description='E-mail address of contact researcher'
    )
    flag_for_summary_data: Any | None = Field(
        None,
        description='Flag to identify summary data with specific problems or significance',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#flaga'}},
    )
    growing_season_duration: Any | None = Field(
        None,
        description='Growing season duration',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#gsdu'}},
    )
    growing_season_start_day: Any | None = Field(
        None,
        description='Growing season start day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#gsst'}},
    )
    id: Any = Field(..., description='nglsi-id id')
    maximum_temp_avg_year: Any | None = Field(
        None,
        description='Temperature maximum, yearly average',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tmxy'}},
    )
    minimum_temp_avg_year: Any | None = Field(
        None,
        description='Temperature minimum, yearly average',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tmny'}},
    )
    psychrometer_ventilation: Any | None = Field(
        None,
        description='Psychrometer ventilation (ventilated or natural air flow)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#psyvnt'}
        },
    )
    rainfall_yearly_total: Any | None = Field(
        None,
        description='Rainfall, yearly total',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#raiy'}},
    )
    ref_height_weather_meas: Any | None = Field(
        None,
        description='Reference height for weather measurement',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#refht'}},
    )
    ref_height_windsp_meas: Any | None = Field(
        None,
        description='Reference height for windspeed measurement',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#wndht'}},
    )
    researcher_first_name: Any | None = Field(
        None, description='First name of contact researcher'
    )
    researcher_last_name: Any | None = Field(
        None, description='Last name of contact researcher'
    )
    solar_rad_yearly_avg: Any | None = Field(
        None,
        description='Solar radiation, yearly average',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sray'}},
    )
    source_daily_weather: Any | None = Field(
        None,
        description='Source of daily weather data for calculated means or weather generator parameters',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_source'}
        },
    )
    start_yr_weather_summary: Any | None = Field(
        None,
        description='Start of summary period weather summary',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#start_yr'}
        },
    )
    temp_amplit_month_avg: Any | None = Field(
        None,
        description='Temperature amplitude (peak to trough) of 12 monthly averages',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tamp'}},
    )
    temperature_avg_year: Any | None = Field(
        None,
        description='Temperature average for whole year',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tav'}},
    )
    temperature_sensor_ht: Any | None = Field(
        None,
        description='Weather station temperature sensor height',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#temht'}},
    )
    type: Any = Field(..., description='nglsi-id type, has to be WeatherStation')
    weather_id: Any | None = Field(
        None,
        description='unique id to link to weather data',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#wid'}},
    )
    weather_sta_description: Any | None = Field(
        None, description='Description of the weather station'
    )
    weather_sta_elevation: Any | None = Field(
        None,
        description='Elevation of weather station',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_elev'}
        },
    )
    weather_sta_latitude: Any | None = Field(
        None,
        description='Latitude of station, degrees decimal with North as positive value',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_lat'}
        },
    )
    weather_sta_longitude: Any | None = Field(
        None,
        description='Longitude of station, degrees decimals with East as positive value',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_long'}
        },
    )
    weather_station_id: Any | None = Field(
        None,
        description='Weather station identifier to link to site information',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_id'}
        },
    )
    weather_station_name: Any | None = Field(
        None,
        description='Weather station name',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_name'}
        },
    )
    weather_station_site: Any | None = Field(
        None,
        description='Name and location of site for weather data',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_site'}
        },
    )
    wsta_loc_2nd_level: Any | None = Field(
        None,
        description='Second admin level for location of site for soil profile (usually state or province)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_loc_2'}
        },
    )
    wsta_loc_3rd_level: Any | None = Field(
        None,
        description='Third admin level for location of site for soil profile (usually county or municipality)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_loc_3'}
        },
    )
    wsta_location_country: Any | None = Field(
        None,
        description='First admin for location of site for soil profile (usually country)',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_loc_1'}
        },
    )


class DailyWeather(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    ambient_co2_conc: Any | None = Field(
        None,
        description='CO2, ambient',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#aco2'}},
    )
    cloudiness_factor: Any | None = Field(
        None,
        description='Cloudiness factor, relative',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#cldd'}},
    )
    co2_conc_atmosphere_daily: Any | None = Field(
        None,
        description='CO2 concentration, atmospheric average over day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#co2d'}},
    )
    day_of_year: Any | None = Field(
        None,
        description='Day of year for daily weather record',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#wtdoy'}},
    )
    daylength_3_deg: Any | None = Field(
        None,
        description='Daylength (3 deg basis)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#da3d'}},
    )
    daylength_sunrise_sunset: Any | None = Field(
        None,
        description='Daylength (sunrise-sunset)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#dayd'}},
    )
    daylength_twilight_basis: Any | None = Field(
        None,
        description='Daylength (twilight to twilight)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#twld'}},
    )
    dry_bulb_temper_avg_day: Any | None = Field(
        None,
        description='Temperature, dry-bulb, daily average',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tdry'}},
    )
    evaporation_pan: Any | None = Field(
        None,
        description='Evaporation,pan',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#evap'}},
    )
    flag_for_weather_data: Any | None = Field(
        None,
        description='Flag to identify daily weather data with specific problems or significance',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#flagw'}},
    )
    id: Any = Field(..., description='nglsi-id id')
    max_temp_average: Any | None = Field(
        None,
        description='Temperature of air, maximum, averaged over time period (e.g., 5 days)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tmxa'}},
    )
    maximum_temperature: Any | None = Field(
        None,
        description='Temperature of air, maximum',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tmax'}},
    )
    min_temp_average: Any | None = Field(
        None,
        description='Temperature of air, minimum, averaged over time period (e.g., 5 days)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tmna'}},
    )
    minimum_temperature: Any | None = Field(
        None,
        description='Temperature of air, minimum',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tmin'}},
    )
    par_photon_flux_density: Any | None = Field(
        None,
        description='PAR or photon flux density',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#pard'}},
    )
    radiation_shortwave: float = Field(
        ...,
        description='Solar radiation, daily shortwave',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#dtr'}},
    )
    rain_snow_fall: float = Field(
        ...,
        description='Rainfall, including moisture in snow, in one day',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#rain'}},
    )
    rainfall: Any | None = Field(
        None,
        description='Rainfall',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#pred'}},
    )
    relative_humidity_avg: Any | None = Field(
        None,
        description='Realtive humidity, average daily value',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#rhavd'}},
    )
    relative_humidity_max: Any | None = Field(
        None,
        description='Relative humidity, maximum daily value',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#rhmxd'}},
    )
    relative_humidity_min_: Any | None = Field(
        None,
        alias='relative_humidity_min ',
        description='Relative humidity at maximum daily temperature (or minimum daily relative humidity)',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#rhumd'}},
    )
    soil_temperature_0_5: Any | None = Field(
        None,
        description='Soil temperature, 0-5 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts1d'}},
    )
    soil_temperature_120_150: Any | None = Field(
        None,
        description='Soil temperature, 120-150 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts8d'}},
    )
    soil_temperature_150_180: Any | None = Field(
        None,
        description='Soil temperature, 150-180 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts9d'}},
    )
    soil_temperature_15_30: Any | None = Field(
        None,
        description='Soil temperature, 15-30 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts3d'}},
    )
    soil_temperature_180_210: Any | None = Field(
        None,
        description='Soil temperature, 180-210 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts10d'}},
    )
    soil_temperature_30_45: Any | None = Field(
        None,
        description='Soil temperature, 30-45 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts4d'}},
    )
    soil_temperature_45_60: Any | None = Field(
        None,
        description='Soil temperature, 45-60 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts5d'}},
    )
    soil_temperature_5_15: Any | None = Field(
        None,
        description='Soil temperature, 5-15 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts2d'}},
    )
    soil_temperature_60_90: Any | None = Field(
        None,
        description='Soil temperature, 60-90 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts6d'}},
    )
    soil_temperature_90_120: Any | None = Field(
        None,
        description='Soil temperature, 90-120 cm',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#ts7d'}},
    )
    solar_radiation: Any | None = Field(
        None,
        description='Solar radiation',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#srad'}},
    )
    sunshine_duration: Any | None = Field(
        None,
        description='Sunshine duration over 24 h period',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#sunh'}},
    )
    temp_average_daily: float = Field(
        ...,
        description='Temperature of air, average daily',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tavd'}},
    )
    temp_avg_daily_air: Any | None = Field(
        None,
        description='Temperature, average daily air, growth',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tgad'}},
    )
    temp_avg_daylight: Any | None = Field(
        None,
        description='Temperature of air, average during daylight hours',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tdyd'}},
    )
    temp_avg_daylight_air: Any | None = Field(
        None,
        description='Temperature, average air, daylight hours',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tgrd'}},
    )
    temperature_dewpoint: Any | None = Field(
        None,
        description='Temperature, dewpoint',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#tdew'}},
    )
    temperature_wet_bulb: Any | None = Field(
        None,
        alias='temperature_wet-bulb',
        description='Temperature, wet-bulb',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#twet'}},
    )
    type: Any = Field(..., description='nglsi-id type, has to be DailyWeather')
    vapor_pressure: Any | None = Field(
        None,
        description='Vapor pressure, average daily',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#vprsd'}},
    )
    weather_date: date_aliased = Field(
        ...,
        description='Date for daily weather, field observations, etc.',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#w_date'}
        },
    )
    weather_id: Any | None = Field(
        None,
        description='unique id to link to weather data',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#wid'}},
    )
    weather_station_id: Any | None = Field(
        None,
        description='Weather station identifier to link to site information',
        json_schema_extra={
            'externalDocs': {'url': 'http://purl.org/icasa/core#wst_id'}
        },
    )
    wind_speed_daily: Any | None = Field(
        None,
        description='Wind speed, daily',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#wind'}},
    )
    year: Any | None = Field(
        None,
        description='Year (4 digits) for daily weather data',
        json_schema_extra={'externalDocs': {'url': 'http://purl.org/icasa/core#wtyr'}},
    )


class Eo(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    id: Any = Field(..., description='nglsi-id id')
    leaf_area_index: Any | None = Field(
        None, description='Leaf area index on a given day'
    )
    observation_date: date_aliased = Field(
        ..., description='Observation date of eo data'
    )
    type: Any = Field(..., description='nglsi-id type, has to be Eo')


class Sample(BaseModel):
    agriparcel: str = Field(..., description='Reference to the AgriParcel')
    grid_id: Any | None = Field(
        None, description='Id to locate sample on chosen grid, e.g. h3 id'
    )
    id: Any = Field(..., description='nglsi-id id')
    location: Any | None = Field(
        None, description='Geometry of the sample, e.g. Point or Polygon'
    )
    sampling_date: date_aliased = Field(..., description='Sampling date')
    soil_organic_C_perc_layr: Any | None = Field(
        None,
        description='Total soil organic carbon by layer, expressed as g[C]/100g[soil]',
    )
    soil_organic_matter_layer: Any | None = Field(
        None, description='Total soil organic matter by layer'
    )
    soil_pH_in_buffer: Any | None = Field(
        None,
        description='pH of soil measured in buffer solution, from profile description',
    )
    soil_pH_in_water: Any | None = Field(
        None, description='pH of soil in water, from profile description'
    )
    total_biomass_dry_wt: Any | None = Field(
        None, description='Total biomass without senesced material (dry weight, kg/ha)'
    )
    type: Any = Field(..., description='nglsi-id type, has to be Sample')


class SimulationDaily(BaseModel):
    agriparcel: Any = Field(..., description='Reference to the AgriParcel')
    grain_N_conc: Any | None = Field(None, description='Grain N concentration')
    grain_dry_weight: Any | None = Field(None, description='Grain dry weight')
    id: Any = Field(..., description='nglsi-id id')
    leaf_area_index: Any | None = Field(None, description='Leaf area index')
    roots_dry_weight: Any | None = Field(None, description='Roots dry weight')
    simulated_date: Any | None = Field(None, description='Simulated date')
    simulation_end_date: Any | None = Field(None, description='Simulation end date')
    simulation_id: Any | None = Field(None, description='Simulation ID')
    simulation_model: Any | None = Field(None, description='Simulation model')
    simulation_name: Any | None = Field(None, description='Simulation name')
    simulation_notes: Any | None = Field(None, description='Simulation notes')
    simulation_start_date: Any | None = Field(None, description='Simulation start date')
    tops_dry_weight: Any | None = Field(
        None, description='Tops (leaves+stems+grains) dry weight'
    )
    type: Any = Field(..., description='nglsi-id type, has to be SimulationDaily')


class SimulationSummary(BaseModel):
    N_uptake_during_season: Any | None = Field(
        None, description='N uptake during season'
    )
    agriparcel: Any = Field(..., description='Reference to the AgriParcel')
    anthesis_date: Any | None = Field(None, description='Growth stage date, anthesis')
    emergence_date: Any | None = Field(None, description='Growth stage date, emergence')
    harvest_operations_date: Any | None = Field(
        None, description='Growth stage date, harvest'
    )
    harvest_yield_harvest_dw: Any | None = Field(
        None, description='Harvested yield at harvest, dry weight'
    )
    id: Any = Field(..., description='nglsi-id id')
    leaf_area_index_maximum: Any | None = Field(
        None, description='Maximum leaf area index'
    )
    physiologic_maturity_dat: Any | None = Field(
        None, description='Growth stage of physiol. maturity, as date'
    )
    planting_date: Any | None = Field(None, description='Planting or sowing date')
    simulation_end_date: Any | None = Field(None, description='Simulation end date')
    simulation_id: Any | None = Field(None, description='Simulation ID')
    simulation_model: Any | None = Field(None, description='Simulation model')
    simulation_name: Any | None = Field(None, description='Simulation name')
    simulation_notes: Any | None = Field(None, description='Simulation notes')
    simulation_start_date: Any | None = Field(None, description='Simulation start date')
    transpiration_cumulative: Any | None = Field(
        None, description='Transpiration, cumulative over season'
    )
    type: Any = Field(..., description='nglsi-id type, has to be SimulationSummary')


class ModelCalibration(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    crop_common_name: Any | None = Field(None, description='ICASA crop common name')
    crop_name_in_model: Any | None = Field(
        None, description='Name of the crop in defined model'
    )
    cultivar_name: Any | None = Field(None, description='ICASA cultivar name')
    cultivar_name_in_model: Any | None = Field(
        None, description='Name of the cultivar in defined model'
    )
    id: Any = Field(..., description='nglsi-id id')
    model_name: Any | None = Field(None, description='Name of the model')
    parameter_dict: Any | None = Field(
        None, description='Dictionary of calibrated parameters'
    )
    type: Any = Field(..., description='nglsi-id type, has to be ModelCalibration')


class AgriFarm(BaseModel):
    agriparcel: Any | None = Field(
        None, description='ngsi-ld id of upper level agriparcel'
    )
    id: Any = Field(..., description='nglsi-id id')
    legalid: Any | None = Field(None, description='Legal id of the farm')
    type: Any = Field(..., description='nglsi-id type, has to be AgriFarm')


class FieldParcel(BaseModel):
    agriparcel: Any | None = Field(None, description='Reference to the AgriParcel')
    area: confloat(ge=0.0) | None = Field(
        None, description='The area of the parcel nominally in square meters.'
    )
    farm: str | None = Field(None, description='Reference to farm.')
    id: Any = Field(..., description='nglsi-id id')
    location: Any = Field(
        ...,
        description='GeoProperty. Geojson reference to the item.',
        title='GeoJSON Polygon',
    )
    name: Any | None = Field(None, description='Name of the parcel')
    parcelid: Any | None = Field(None, description='Parcel id')
    resolution: Any | None = Field(
        None, description='Spatial resolution, especially for h3 cells'
    )
    spatial_category: Any | None = Field(
        None, description="Parcel type. 'Enum:' `base`, `growth`, `h3`"
    )
    type: Any = Field(..., description='nglsi-id type, has to be FieldParcel')
    year: Any | None = Field(None, description='Registration year')
