version: '3.8'

services:
    devcontainer:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      volumes:
        - ../../:/workspaces
      tty: true
    #network_mode: service:db
    #command: sleep infinity
